baseurl: 'https://www.xaprb.com/'
buildFuture: true
blackfriday:
  plainIdAnchors: true
theme: story
googleAnalytics: "UA-101883-1"
title: "Baron Schwartz's Website"
menu:
   main:
   - name: Talks
     title: Talks
     url: /talks/
   social:
   - name: linkedin
     title: "fab fa-linkedin-square"
     url: "https://linkedin.com/in/xaprb"
   - name: twitter
     title: "fab fa-twitter-square"
     url: "https://twitter.com/xaprb"
params:
   author: "Baron Schwartz"
   Amazon: "xaprb-20"
   Email: "&098;&097;&114;&111;&110;&064;&118;&105;&118;&105;&100;&099;&111;&114;&116;&101;&120;&046;&099;&111;&109;"
MetaDataFormat: "yaml"
Paginate: 20
rssLimit: 20
Taxonomies:
   category: "categories"
   tag: "tags"
outputs:
   home:
      - HTML
      - JSON
      - RSS
   page:
      - HTML
   section:
      - HTML
      - RSS
   taxonomy:
      - HTML
      - RSS
   taxonomyTerm:
      - HTML
      - RSS
Related:
   threshold: 50
   toLower: true
   indices:
      - name: keywords
        weight: 100
      - name: categories
        weight: 50
      - name: description
        weight: 50
      - name: title
        weight: 100
---
